import "./globals.css";
import ClientLayout from "./client-layout";
import Sidebar from "./components/Sidebar";


export const metadata = {
  title: "VIDE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white text-black dark:bg-gray-900 dark:text-white transition-colors duration-300">
            <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
